name: Carshaming
favicon: null
layout_spectrum: 0.51619
typography_spectrum: 0.2593242027796805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d7172'
    - '#fbffff'
    - '#6aa0e0'
    - '#0d131d'
    - '#3a4f6d'
  brandStrength: 0.5
  lightness: 0.6986019406467676
  saturation: 0.8009735059458762
  rhythmicContrast: 0.7694179199170321
purpose: []
